import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/layout/Navbar";
import { getServerSession } from "next-auth";
import Provider from "./Provider";
import { options } from "./lib/authoptions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen overflow-x-hidden custom-scrollbar-hidden antialiased flex justify-center`}
      >
      <Provider session={session}>
        <div className="w-full sm:w-[402px] min-h-screen bg-[#EDF1F9]">
            <Navbar />
            <div className="p-3 h-full pb-32">
              {children}
            </div>
        </div>
      </Provider>
      </body>
    </html>
  );
}